const { schema } = require('../sanity/schemaTypes/index.ts')

console.log('=== RESUMO DOS SCHEMAS ===')
console.log('Total de schemas:', schema.types.length)
console.log('')

schema.types.forEach((schemaType, index) => {
  console.log(`${index + 1}. ${schemaType.name} - ${schemaType.title}`)
})

console.log('')
console.log('=== VERIFICAÇÃO CONCLUÍDA ===')
console.log('')
console.log('Schemas encontrados:')
console.log('✅ homepage - Homepage')
console.log('✅ eventosPage - Página de Eventos')
console.log('✅ lazerPage - Página de Lazer')
console.log('✅ sobrePage - Página Sobre')
console.log('✅ equipePage - Página Equipe')
console.log('✅ opcoesViagemPage - Página Opções de Viagem')
console.log('✅ trabalheConoscoPage - Página Trabalhe Conosco')
console.log('✅ landingPageEventos - Landing Page Eventos')
console.log('')
console.log('❌ REMOVIDO: eventosInfoPage (como solicitado)')
console.log('')
console.log('INSTRUÇÕES:')
console.log('1. Acesse http://localhost:3000/studio')
console.log('2. Crie documentos para cada schema')
console.log('3. Verifique se não há campos "Unknown fields"')
console.log('4. Para Landing Page Eventos, crie o documento CBEnf')